version: '2'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    environment:
      - MYSQL_DATABASE=concerto
      - MYSQL_USER=concerto
      - MYSQL_PASSWORD=qazplm123!@#
      - MYSQL_ROOT_PASSWORD=qazplm123!@#
      - TZ=Asia/Kolkata
    volumes:
      - ./data/mysql:/var/lib/mysql

  concerto:
    image: campsych/concerto-platform:master
    container_name: concerto
    restart: on-failure
    volumes:
      - ./data/concerto:/data
    environment:
      - CONCERTO_PASSWORD=admin
      - CONCERTO_CONTENT_URL=.
      - CONCERTO_PLATFORM_URL=/
      - CONCERTO_GIT_REPOSITORY_PATH=/data/git
      - DB_HOST=database
      - DB_PASSWORD=qazplm123!@#
      - TZ=Asia/Kolkata
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: on-failure
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
    ports:
      - "8080:80"
